### ISSUE TITLE
code for the webshop is missing 

### ISSUE THREAD

**Issue by JosephCurwin** [andyz245/LanguageAgentTreeSearch#1]
I think you forgot to include the code for the webshop the agent is interacting with 
http://127.0.0.1:5000/

**Comment by andyz245** [comment]
Thanks for catching this! Added instructions for installing and running webshop in the readme. The exact link will depend on your port after setting up the environment locally.

**Comment by JosephCurwin** [comment]
instruction given worked for solving the issue
