### ISSUE TITLE
Having trouble running lats on hotpot in 'standard' prompt sample mode

### ISSUE THREAD

**Issue by dxing-cs** [andyz245/LanguageAgentTreeSearch#13]
Hi andyz245, 

Thank you very much for your excellent work! 

I have some trouble running lats on hotpot. When I run your code in the CoT prompt mode, it works fluently. However, if I switch the mode to 'standard', I find that the code will be caught in a dead loop. After some debugging, I noticed that the problem occurs at this line: 

https://github.com/andyz245/LanguageAgentTreeSearch/blob/e08d36fee744c6b8edbe75c448766fb556b9f3ed/hotpot/lats.py#L305C15-L305C15

where the `sampled_action` fails to parse a valid action (probably because the response of GPT does not contain words such as `Search[something]`?) and therefore MCTS cannot successfully generate new states. Do you have any suggestions on this issue?

**Comment by andyz245** [comment]
Hi, 

Thanks for reaching out. The current code is only designed to run it in "CoT" mode, which actually corresponds to ReAct (sorry for the confusion). The standard setting corresponds to CoT, which is not supported by thee current code. If you need to run the code with CoT (and not ReAct), I can try to reimplement it.

**Comment by andyz245** [comment]
closing this for now
