### ISSUE TITLE
Programming trajectories

### ISSUE THREAD

**Issue by jialin-song** [andyz245/LanguageAgentTreeSearch#16]
Thanks for making your work open source! I want to ask which files in the programming trajectories folder (`programming/root/`) contain solutions for the pass@1 numbers for HumanEval and MBPP reported in the paper?

Thanks!

**Comment by andyz245** [comment]
Hi,
The results for GPT-4 are in test_mcts_hard_acc_full_4tst_temp_gpt4 and the results for GPT-3.5 are in test_mcts_hard_acc_full_4tst_temp_2 

Hope this helps!

**Comment by jialin-song** [comment]
Thanks for your response! Is it correct that the the MBPP result in the paper was produced with only GPT-3.5?

**Comment by andyz245** [comment]
Yes, we only have results for GPT-3.5 on MBPP

**Comment by jialin-song** [comment]
Thanks! For the GPT-4 results on HumanEval, I am having trouble getting the same pass@1 number as reported in the paper. I want to make sure I am doing things correctly: specifically, I am extracting solutions from `test_mcts_hard_acc_full_4tst_temp_gpt4/humaneval-py._mcts_8_gpt-4_pass_at_k_1_py.jsonl` by collecting the "solution" key for each entry. Then I used the `evalplus` package (https://github.com/evalplus/evalplus) to evaluate extracted solutions. Evalplus reports both the base accuracy (using the original test cases in the dataset) and their enhanced version. Your code suggests you obtained results with the original test cases.

When I did so, I expected the pass@1 to be around 92.1% (since you used 160 problems out of 164, so 94.4 * 160 / 164), but instead I got only 73.8%. Is there anything I am missing in my evaluation pipeline? I attached my extracted programs. To run eval you need to change the extension from `.json` to `.jsonl`, as github doesn't support jsonl file upload. Thanks for your time.
[LATS_openai_humaneval_programs.json](https://github.com/andyz245/LanguageAgentTreeSearch/files/13942078/LATS_openai_humaneval_programs.json)
