### ISSUE TITLE
Question regarding Node Evaluation Phase

### ISSUE THREAD

**Issue by andreasbinder** [andyz245/LanguageAgentTreeSearch#17]
First of all, thx a lot for this interesting paper and the code to follow along your ideas!

I was also looking through the RAP paper, and it seems that you specifically highlighted the evaluation phase in the phases of MCTS. For the reflection, I understand why you highlight it specifically, but for the evaluation phase I am a bit confused. Is there something inherently special about the evaluation phase in LATS? As far as I understand MCTS, in the expansion phase there is a reward calculation happening, estimating which action to continue from the current node defined from the selection phase before (and this is done in RAP too).

It would be amazing if you could highlight that for me; thank you already :)

**Comment by andyz245** [comment]
Thanks for reaching out, the evaluation for LATS is a bit different than in RAP, we specifically ask the agent to score its own responses, but after environment feedback is obtained. This makes the evaluation more accurate since it involves external feedback. These values are assigned to the node states to guide the search process.

**Comment by andreasbinder** [comment]
Awesome! Thx for the quick response :) Two short follow-up questions:

- Does this replace the reward calculation before the state transition or are both rewards used?
- Finally, what would be environment feedback for HotpotQA? The ground-truth whether eg a search got the correct sources?

**Comment by andyz245** [comment]
It depends on the environment, but for cases where rewards are available they are used for the backpropagation step, which updates the state values. 

We use an oracle setup for HotPotQA, so there is ground-truth feedback.
