### ISSUE TITLE
Can we add JS capabilities to programming?

### ISSUE THREAD

**Issue by aneeqahsan01** [andyz245/LanguageAgentTreeSearch#19]
Hi, I've noticed that only 3 languages (py, rs and go) are supported in this framework, can we add javascript capabilities to this for simple and reflexion strategy ? 

I would love to know which playground you think would be best for your framework?

Thanks ! Great work!

**Comment by andyz245** [comment]
Hi, thanks for reaching out but I don't have any plans to update the codebase. It's just for running the experiments in the paper. But LangChain recently implemented LATS into LangGraph, which should be more general/accessible. 

https://github.com/langchain-ai/langgraph/blob/main/examples/lats/lats.ipynb
