### ISSUE TITLE
 Hello, I don’t understand how hotpotqa’s reward is scored. It seems that when searching the wiki, the reward is not set to 1. What I always get is reward=0. Can you explain how to reward qa? Thank you.

### ISSUE THREAD

**Issue by zouhuigang** [andyz245/LanguageAgentTreeSearch#20]
Hello, I don’t understand how hotpotqa’s reward is scored. It seems that when searching the wiki, the reward is not set to 1. What I always get is reward=0. Can you explain how to reward qa? Thank you.

![image](https://github.com/andyz245/LanguageAgentTreeSearch/assets/15059874/271f356d-5be1-46cf-b2eb-aacad931b569)

**Comment by dailiokok** [comment]
Hello, sorry to bother you. I have the same question as you. I would like to ask you, do you understand how to assign the reward?
