### ISSUE TITLE
Please consider re-evaluating your HumanEval results.

### ISSUE THREAD

**Issue by Honka1StarRail** [andyz245/LanguageAgentTreeSearch#22]
Dear Authors,

Please consider re-evaluating your HumanEval results. Your scores are not Pass@1 but rather Pass@k, where k ranges from 5 to 40, according to your codes (Actually, we found this problem half a year before).

As more papers cite your work and report your Pass@1 results, it would be better to take this into a more serious consideration.

**Comment by andyz245** [comment]
Hi, I've reviewed the code you pointed out and yes, it is Pass@1. We follow Code-T and Reflexion and use LLM-generated synthetic tests as a source of feedback during search. The real tests for evaluation are only executed once, so it is Pass@1.
