### ISSUE TITLE
Webshop is too slow

### ISSUE THREAD

**Issue by SpaceLearner** [andyz245/LanguageAgentTreeSearch#32]
Dear author,

It is very nice work. In my environment, it takes around 1.5h to run one example of WebShop. It's too slow and is there any way to improve the efficiency? What is the normal time it takes to run WebShop ?

**Comment by andyz245** [comment]
Thank you! That's unexpected, but it does take longer than baselines for each example. You can change the number of iterations and other hyperparameters to reduce the speed.
