### ISSUE TITLE
Is the object of reflection for multiple nodes or a single node

### ISSUE THREAD

**Issue by zulihit** [andyz245/LanguageAgentTreeSearch#34]
Hello, I would like to inquire about the difference between the official implementation and the Langgraph implementation. I noticed that the rating mentioned in the paper is for the entire chain (path), which includes multiple nodes and ultimately returns the entire chain as the answer? In Langgraph, it seems to rate individual nodes and, in the end, return the content of the last node.
I'm not sure if I misunderstood, could you please answer this question? Thank you very much for your help

**Comment by andyz245** [comment]
Hi, the value function is for individual nodes, each node is scored separately.
