### ISSUE TITLE
Incorrect Simulation Loop Placement in MCTS Expansion Phase

### ISSUE THREAD

**Issue by zzfoo** [andyz245/LanguageAgentTreeSearch#35]
https://github.com/lapisrocks/LanguageAgentTreeSearch/blob/853d81614607dd27433faf17c7b0a7d660f95d22/programming/mcts.py#L151-L243

The **Simulation** loop in the `run_mcts` function is incorrectly placed inside the `for _ in range(n)` loop of the **Expansion** phase. This causes the simulation to iterate over all child nodes of the current node during each iteration of the expansion loop, leading to redundant simulations and incorrect behavior.

**Comment by myhakureimu** [comment]
Yes, I found the same issue. Hope the author would fix this.
