### ISSUE TITLE
Is it correct to use the ground-truth answer on HotpotQA during MCTS?

### ISSUE THREAD

**Issue by JianGuanTHU** [andyz245/LanguageAgentTreeSearch#6]
I note that the ground-truth answer is used to compute the reward [(wrappers.py#111)](https://github.com/andyz245/LanguageAgentTreeSearch/blob/main/hotpot/wrappers.py#111). But I don't think the LM should get feedback from the ground-truth answer. Do I understand correctly?

**Comment by andyz245** [comment]
The LM is not provided with the ground-truth answer but the feedback will indicate if it's answer is correct or not. This is possibly a flaw with using reflections in this setting.

**Comment by JianGuanTHU** [comment]
Thank you very much for your quick response! But I am still confused. Actually, the LM should not know anything about the ground-truth answer. If the ground-truth answer is used to tell the LM whether its reasoning trajectory is correct (reward=1 if correct else 0), the LM will ideally improve itself.

BTW, the reward will be used for backpropagation to update all values in the whole trajectory, do I understand right?

**Comment by andyz245** [comment]
Yes, that's correct. The label (correct or not) is the main source of feedback, which lets the LLM improve by trying different answers. And yes, all nodes in the trajectory that led up to the terminal node will be updated with the reward. Happy to answer any further questions.

**Comment by andyz245** [comment]
Closing this for now

**Comment by pxspxspxs1** [comment]
Hello！ I also think that in real-world question-answering scenarios, the ground-truth labels should not be used as the source of reward, because there is no correct answer in real-world situations. I'm not sure if this can be considered label leakage. I look forward to your response.
