### ISSUE TITLE
Lets package Lats for pypi

### ISSUE THREAD

**Issue by maxsu** [andyz245/LanguageAgentTreeSearch#8]
With your permission, I am working to package LATS for pypi. 

This has a few requirements:

1. Unify the Lats, Hotpot, and WebShop modules under a /src folder
2. Use a pip-compatible Pyproject.toml to represent project tools, configurations, and entry points
3. Update documentation to represent the new deployment instructions (ie, pip install LATS)

Would you consider a PR here?

**Comment by andyz245** [comment]
Sure that's fine. Thanks!

**Comment by andyz245** [comment]
closing this for now
